FROM openjdk:11-jre-slim-stretch

LABEL name "ramiel-server"
LABEL version "3.2.0.3"
LABEL maintainer "Euni <vescalaw@gmail.com>"

WORKDIR /opt/Lavalink

RUN apt-get update && apt-get install -y curl

RUN curl -o Lavalink.jar https://ci.fredboat.com/repository/download/Lavalink_Build/6318:id/Lavalink.jar?guest=1

EXPOSE 2333

CMD [ "java", "-jar", "-Xmx768m", "Lavalink.jar" ]
